name: Create Release

on:
  # Trigger the workflow every time you push to the `main` branch
  # Using a different branch name? Replace `main` with your branch’s name
  push:
    tags:
      - '**'
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: true
      - name: Build
        run: pnpm build
      - name: Create Mod Zip
        run: |
          mkdir server-config && \
          mv dist server-config/ && \
          mv manifest.yaml server-config/ && \
          zip -r Server-Config.zip server-config
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            Server-Config.zip
